name: CI

on:
  push:
    branches: [ master ]
  pull_request: {}

jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [14.19.0]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        # not caching node_modules because `npm ci` removes it
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm ci
    - name: Copy secrets example file
      run: npm run copy-secrets
    - name: Run Jest tests
      run: npm run silent-test
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
  cypress:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [14.19.0]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        # not caching node_modules because `npm ci` removes it
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm ci
    - name: Copy secrets example file
      run: npm run copy-secrets
    - name: Prepare for Cypress tests
      run: npm run cypress:prepare-ci
    - name: Run Cypress tests
      run: npm run cypress:ci
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        directory: 'cypress-coverage'
  deploy:
    if: success() && github.ref == 'refs/heads/master' # only run on master success
    needs: [jest, cypress] # only run after jest and cypress jobs complete
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Push to ECC
      run: |
        git remote add ecc ssh://git@git.earthdata.nasa.gov:7999/edsc/edsc.git
        git fetch ecc "+refs/heads/*:refs/remotes/origin/*"

        git fetch --unshallow || true
        echo "GITHUB_COMMIT=$GITHUB_SHA"
        git push ecc $GITHUB_SHA:refs/heads/serverless
